package com.DS1.OOP.Polymorphism8;

public class Main {
    public static void main(String[] args) {
        Shapes shape = new Shapes();
        Circle circle = new Circle();
        Square square = new Square();
        Triangle triangle = new Triangle();

        Shapes circle2 = new Circle();
        // TYPE OF REFERENCE VARIABLE AS PARENT CLASS AND OBJECT IS OF TYPE SUB CLASS.




//        circle.area();
//        circle2.area();
        // WE NEED AN AREA FUNCTION IN SHAPES CLASS BECAUSE IT WILL FIRST CHECK WHETHER AREA IS AVAILABLE OR NOT.
        // AT RUNTIME THROUGH DYNAMIC METHOD DISPATCH JAVA WILL DETERMINE WHICH METHOD TO RUN.
        // IT WILL ALWAYS DEPEND ON TYPE OF OBJECT THROUGH WHICH IT WAS CREATED.


        Shapes square2 = new Square();

        square2.greeting();

        // STATIC METHODS DOES NOT DEPEND ON OBJECTS.
        // SO NO MATTER FROM WHICH OBJECT YOU CALL THE GREETING METHOD IT WILL RUN IN PARENT CLASS.
        // SO THERE IS NO POINT IN OVERRIDING IT IN CHILD CLASS.
        // MAIN REASON IS STATIC DOES NOT DEPEND ON OBJECTS SO IT CAN'T BE OVERRIDDEN.

        // OVERRIDING DEPEND ON OBJECTS AND STATIC DOES NOT DEPEND ON OBJECTS.
        // HENCE, STATIC METHOD CANNOT BE OVERRIDDEN BUT IT CAN BE INHERITED.
        // EXPLANATION DOWN AT END.

        Square square3 = new Square();
        square3.greeting();

        // HERE OBJ TYPE IS SQUARE.
        // SO ASSUME THERE IS ANOTHER CLASS WHICH IS SUBCLASS OF SQUARE.
        // NOW IN THAT CLASS STATIC GREETING METHOD IS CREATED.
        // NOW IF TYPE OF REF VARIABLE IS SQUARE AND OBJ TYPE IS SUBCLASS.
        // THEN ON CALLING GREETING METHOD IT WILL CALL THE METHOD PRESENT IN SQUARE CLASS.
        // GREETING METHOD IN ITS SUBCLASS WILL NOT OVERRIDE THE METHOD IN SQUARE CLASS.
        // BECAUSE IT DOES NOT DEPEND ON OBJECTS AS IT IS STATIC.

        // EXPLAIN.
        // IF IN THIS EXAMPLE WHERE REF AND OBJ TYPE ARE SQUARE ITSELF.
        // IF SQUARE CLASS DOES NOT HAVE ANY GREETING METHOD IT WILL CALL THE ONE PRESENT IN ITS SUPER CLASS.


    }
}
